name: Docker Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/designerwang/alist-gallery:${{ github.ref_name }}
            docker.io/designerwang/alist-gallery:latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build binaries for multiple platforms
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/alist-gallery-darwin-amd64-${GITHUB_REF_NAME#refs/tags/}
          GOOS=linux GOARCH=amd64 go build -o dist/alist-gallery-linux-amd64-${GITHUB_REF_NAME#refs/tags/}
          GOOS=windows GOARCH=amd64 go build -o dist/alist-gallery-windows-amd64-${GITHUB_REF_NAME#refs/tags/}.exe

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/alist-gallery-darwin-amd64-${GITHUB_REF_NAME#refs/tags/}
          asset_name: alist-gallery-darwin-amd64-${GITHUB_REF_NAME#refs/tags/}
          content_type: application/octet-stream

      - name: Upload release assets (Linux)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/alist-gallery-linux-amd64-${GITHUB_REF_NAME#refs/tags/}
          asset_name: alist-gallery-linux-amd64-${GITHUB_REF_NAME#refs/tags/}
          content_type: application/octet-stream

      - name: Upload release assets (Windows)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/alist-gallery-windows-amd64-${GITHUB_REF_NAME#refs/tags/}.exe
          asset_name: alist-gallery-windows-amd64-${GITHUB_REF_NAME#refs/tags/}.exe
          content_type: application/octet-stream
