name: Docker Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebp-dev musl-dev gcc musl-tools

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/designerwang/alist-gallery:${{ github.ref_name }}
            docker.io/designerwang/alist-gallery:latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build binaries for multiple platforms
        run: |
          mkdir -p dist
          export CGO_ENABLED=1
          if [[ $GOOS == "darwin" ]]; then
            export CC=clang
          else
            export CC=musl-gcc
          fi
          GOOS=darwin GOARCH=amd64 go build -o dist/alist-gallery-darwin-amd64-${{ github.ref_name }}
          GOOS=linux GOARCH=amd64 go build -o dist/alist-gallery-linux-amd64-${{ github.ref_name }}
          GOOS=windows GOARCH=amd64 go build -o dist/alist-gallery-windows-amd64-${{ github.ref_name }}.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release assets (Darwin)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/alist-gallery-darwin-amd64-${{ github.ref_name }}
          asset_name: alist-gallery-darwin-amd64-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload release assets (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/alist-gallery-linux-amd64-${{ github.ref_name }}
          asset_name: alist-gallery-linux-amd64-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload release assets (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/alist-gallery-windows-amd64-${{ github.ref_name }}.exe
          asset_name: alist-gallery-windows-amd64-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream